/**
 * ============================================================
 * CONFIG.GS — Central configuration & schema definitions
 * ============================================================
 * Adding a new module/table later only requires adding an
 * entry here, then a matching *.gs module and *.html page.
 * This object is also the single source of truth you'll use
 * to generate CREATE TABLE statements when migrating to MySQL.
 * ============================================================
 */

var APP_CONFIG = {
  SPREADSHEET_ID: '12V1auP9xVsBi-0eR7i7R06T6y0JoRhB0YBNVLDqXhr0', // This project is standalone (not container-bound) — SpreadsheetApp.getActiveSpreadsheet() returns null for it, so this ID is required, not optional
  DEFAULT_PAGE_SIZE: 10,
  APP_NAME: 'Computeraid International M&E System',
  RESET_TOKEN_HOURS: 48,  // how long a "set your password" email link stays valid
  SESSION_HOURS: 12,      // how long a Hub Manager stays logged in
  FIREBASE_APP_URL: 'https://mne-admin.web.app', // Phase 3: the production frontend (see the migration plan) — GAS's own doGet no longer renders pages, only redirects here

  // Fixed "Billed To" block on a Hub-Manager-generated invoice (they
  // invoice Computer Aid International for their stipend / office costs).
  ORG_BILLING: {
    name: 'Computeraid Kenya',
    addressLines: ['Sanlam House, Kenyatta Avenue,', '1st Floor, Suite No. 103.']
  }
};

/**
 * Maps a legacy GAS ?page= key to the equivalent static path on the
 * Firebase-hosted frontend, optionally appending query params (e.g.
 * resetpassword's email/token, or login's reason=timeout). Single
 * source of truth for both Code.gs's doGet redirect and the
 * transactional email link-builders (EmailService.gs, AdminAuth.gs) —
 * keeps the URL scheme in exactly one place.
 */
function getFrontendUrl_(pageKey, params) {
  var path = (pageKey === 'resetpassword') ? '/resetpassword.html'
    : (pageKey === 'login' || pageKey === 'adminlogin' || pageKey === 'managerlogin') ? '/login.html'
    : '/index.html';

  var qs = Object.keys(params || {})
    .filter(function (k) { return params[k]; })
    .map(function (k) { return k + '=' + encodeURIComponent(params[k]); })
    .join('&');

  return APP_CONFIG.FIREBASE_APP_URL + path + (qs ? '?' + qs : '');
}

/**
 * SCHEMA defines every "table" (worksheet) in the system.
 *
 * `autoId` defaults to true, meaning the primary key is generated by
 * DB.generateId() using `idPrefix`/`idPadding` (C001, H001, ...). Set
 * `autoId: false` for tables with a natural key supplied by the caller
 * (e.g. HubManagers is keyed by Email) — DB.insert() will then use the
 * caller-provided value and enforce uniqueness itself.
 */
var SCHEMA = {

  Countries: {
    sheetName: 'Countries',
    primaryKey: 'CountryID',
    idPrefix: 'C',
    idPadding: 3,
    columns: ['CountryID', 'CountryName', 'ISOCode', 'Status', 'DateCreated', 'DateModified'],
    searchableColumns: ['CountryName', 'ISOCode'],
    foreignKeys: {}
  },

  Hubs: {
    sheetName: 'Hubs',
    primaryKey: 'HubID',
    idPrefix: 'H',
    idPadding: 3,
    columns: [
      'HubID', 'HubName', 'CountryID', 'CountyOrState', 'Town', 'Address', 'DateCreated', 'DateModified', 'Status',
      // Appended for per-hub optional tabs (Module: optional tabs). Comma-
      // separated page keys from MANAGER_OPTIONAL_PAGES (Router.gs) this
      // hub's Manager may see — everything else in that list stays
      // greyed out for them until an Admin ticks it here. The compulsory
      // pages (Dashboard/My Projects/Beneficiaries/Hub Usage/My Devices)
      // are never affected by this — see getHubEnabledTabs_ in Hubs.gs.
      'EnabledOptionalTabs'
    ],
    searchableColumns: ['HubName', 'CountyOrState', 'Town'],
    foreignKeys: {
      CountryID: { table: 'Countries', column: 'CountryID' }
    }
  },

  /**
   * HubManagers is keyed by Email (a manager's login identity), not an
   * auto-generated ID — that's what the person actually authenticates
   * with. DB.insert() enforces that no two records can share an Email.
   * Password fields are never sent to the client; see
   * stripSensitiveManagerFields() in Managers.gs.
   */
  HubManagers: {
    sheetName: 'HubManagers',
    primaryKey: 'Email',
    autoId: false,
    columns: [
      'Email', 'FirstName', 'LastName', 'Phone', 'HubID',
      'PasswordHash', 'PasswordSalt', 'MustResetPassword',
      'ResetToken', 'ResetTokenExpiry',
      'Status', 'DateCreated', 'DateModified',
      // Self-service profile fields (ManagerProfile.gs). BankAccountNumber/
      // MobileMoneyNumber are stored in full but a Hub Manager only ever
      // sees their own masked back (getMyManagerProfile) — same
      // maskAccountNumber_ convention FinancialAccounts already uses —
      // Admin/Finance see them in full since they're the ones who'd
      // actually action a payout.
      'Address', 'PhotoUrl',
      'BankName', 'BankAccountName', 'BankAccountNumber',
      'MobileMoneyProvider', 'MobileMoneyName', 'MobileMoneyNumber',
      // Appended for the generated-invoice Terms footer (Module: invoice
      // generation) — the rest of the bank block a payout instruction
      // needs beyond name/account-number. Not sensitive the way the
      // account number is, so these aren't masked.
      'BankCode', 'SwiftCode', 'BankBranch', 'BranchCode'
    ],
    searchableColumns: ['FirstName', 'LastName', 'Email', 'Phone'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * Admins are the system administrators — now a real credential-based
   * login (email + password), replacing the earlier "anyone who opens
   * the URL is trusted as admin via their Google session" assumption.
   * The very first account is created by running createInitialAdmin()
   * once from the Apps Script editor — see AdminAuth.gs. Every other
   * admin account (any AccessLevel) is created from the in-app
   * Administrators page (AdminTeam.gs), SuperAdmin-only.
   */
  Admins: {
    sheetName: 'Admins',
    primaryKey: 'Email',
    autoId: false,
    columns: [
      'Email', 'FirstName', 'LastName', 'PasswordHash', 'PasswordSalt', 'Status', 'DateCreated', 'DateModified', 'ResetToken', 'ResetTokenExpiry',
      // Appended for Module 3 (roles): SuperAdmin sees/does everything
      // and manages other admin accounts; CountryDirector is exactly
      // today's original, unrestricted Admin; MELead/Accountant are each
      // scoped to a narrower page set — see ACCESS_LEVEL_RESTRICTED_PAGES
      // in Router.gs (the real enforcement) and resolveAdminAccessLevel_
      // in AdminAuth.gs (self-heals a blank value on next login rather
      // than needing a manual backfill).
      'AccessLevel',
      // Appended for per-country data scoping: which Country a
      // CountryDirector is restricted to. Blank is a PERMANENT, valid
      // state meaning "unscoped — sees every country," not just a
      // pre-migration default — every account that predates this field
      // keeps working exactly as before until an Admin deliberately
      // assigns one. Only ever consulted for AccessLevel==='CountryDirector';
      // meaningless (never read) for SuperAdmin/MELead/Accountant. See
      // resolveAdminHubScope_ in CountryScope.gs — the real enforcement.
      'CountryID'
    ],
    searchableColumns: ['FirstName', 'LastName', 'Email'],
    foreignKeys: {
      CountryID: { table: 'Countries', column: 'CountryID' }
    }
  },

  /**
   * Lightweight login sessions shared by every credentialed role (Admins
   * and HubManagers today). Kept as a real table rather than
   * CacheService so a session can outlive CacheService's hard 6-hour
   * cap and stays consistent with the rest of the app's "everything is
   * a table" design. See SessionService.gs.
   */
  Sessions: {
    sheetName: 'Sessions',
    primaryKey: 'SessionToken',
    autoId: false,
    columns: ['SessionToken', 'Email', 'Role', 'ExpiresAt', 'DateCreated'],
    searchableColumns: [],
    foreignKeys: {}
  },

  /**
   * A reporting quota is one quarter of one reporting year, e.g. "Q1
   * 2026" — set up by the admin, then used by Hub Managers to file
   * dated projects against. Quarter + YearLabel are never duplicated as
   * a combo (see validateQuotaInput in Quotas.gs); the display label
   * ("Q1 2026") is always computed from the two fields rather than
   * stored redundantly.
   *
   * ProjectYear/QuarterStart/QuarterEnd added later: quarters used to be
   * a fixed Jan-Apr/May-Aug/Sep-Dec calendar split derived from YearLabel
   * alone (still the fallback for any older quota row that predates these
   * columns — see getQuotaDateRange_ in Quotas.gs). New quotas store their
   * actual date range directly, so a "quarter" can start/end whenever a
   * project's real cycle does, not just on calendar-quarter boundaries.
   * ProjectYear is a separate free-text label (not necessarily "YYYY")
   * from YearLabel, which stays for backward-compatible display/sorting.
   */
  ReportingQuotas: {
    sheetName: 'ReportingQuotas',
    primaryKey: 'QuotaID',
    idPrefix: 'Q',
    idPadding: 3,
    columns: ['QuotaID', 'Quarter', 'YearLabel', 'Status', 'DateCreated', 'DateModified', 'ProjectYear', 'QuarterStart', 'QuarterEnd'],
    searchableColumns: ['Quarter', 'YearLabel', 'ProjectYear'],
    foreignKeys: {}
  },

  /**
   * PLACEHOLDER — schema only, not wired up yet. One row per monthly
   * beneficiary report a Hub Manager files against a ReportingQuota for
   * their Hub. Defined now (same pattern as pre-creating Hubs/HubManagers
   * ahead of their own modules in earlier phases) so the next step's
   * progressive add-project form has a stable table to write to. No
   * Projects.gs / UI reads or writes this yet.
   */
  /**
   * A project is a named, dated activity a Hub Manager runs — not a
   * fixed monthly slot. ProjectDate must fall within its ReportingQuota's
   * 3-month window (see getQuotaDateRange_ in Quotas.gs), but multiple
   * projects can share a quota, a month, or even a date.
   */
  Projects: {
    sheetName: 'Projects',
    primaryKey: 'ProjectID',
    idPrefix: 'P',
    idPadding: 4,
    columns: [
      'ProjectID', 'QuotaID', 'HubID', 'ProjectName', 'ProjectDate', 'Cost',
      'TotalNewBeneficiaries', 'Female',
      'Age0to5', 'Age6to10', 'Age11to13', 'Age14to18', 'Age19to23',
      'Age24to28', 'Age29to32', 'Age33to36', 'Age37to64', 'Age65Plus',
      'Status', 'DateCreated', 'DateModified',
      // Added later: a project can span more than one day. ProjectDate
      // keeps its original meaning (the project's START date) so every
      // existing sort/filter/KPI keyed on it keeps working unchanged;
      // ProjectEndDate is optional (blank on rows created before this
      // field existed) and, when set, must be >= ProjectDate and fall
      // within the same reporting quota's window — see
      // validateProjectInput in Projects.gs.
      'ProjectEndDate'
    ],
    searchableColumns: ['ProjectName'],
    foreignKeys: {
      QuotaID: { table: 'ReportingQuotas', column: 'QuotaID' },
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * "Inventory at the Hub" — one row per physical asset/equipment item
   * held at a Hub Manager's own hub (desktops, laptops, printers, solar
   * kit, ...). HubID is resolved server-side from the caller's own Hub
   * Manager session, never supplied by the client — same pattern as
   * Projects. Category/Condition/Status are fixed option lists defined
   * in Inventory.gs (INVENTORY_CATEGORIES/CONDITIONS/STATUSES), not
   * separate lookup tables, since they're a small, stable set.
   * PhotoURL is an optional link to an image (e.g. a Drive share link)
   * rather than a stored file — Sheets-backed tables don't hold blobs.
   */
  Inventory: {
    sheetName: 'Inventory',
    primaryKey: 'InventoryID',
    idPrefix: 'INV',
    idPadding: 4,
    columns: [
      'InventoryID', 'HubID', 'Category', 'ItemName', 'Manufacturer', 'Model',
      'SerialNumber', 'Quantity', 'Condition', 'DateAcquired', 'Status', 'PhotoURL',
      'DateCreated', 'DateModified'
    ],
    searchableColumns: ['ItemName', 'Manufacturer', 'Model', 'SerialNumber'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * "Laptops for Sale" — one row per laptop being resold. The three
   * sub-sections in the UI (Current Stock / Sold / Faulty) are just
   * filtered views of this one table keyed on Status — a laptop can
   * only ever have one Status at a time, so it structurally can never
   * appear in more than one of those views at once. OrderNumber groups
   * laptops added together (manual add = its own single-item batch,
   * spreadsheet import = one shared batch number) per the "allocate an
   * order number to each new stock list" requirement. AssetID/
   * PurchaseOrderNumber/SalesOrderNumber come from the resale system's
   * spreadsheet export (Barcode/purchaseordernum/salesordernum columns)
   * and are optional for manually-added laptops.
   */
  Laptops: {
    sheetName: 'Laptops',
    primaryKey: 'InventoryID',
    idPrefix: 'LAP',
    idPadding: 4,
    columns: [
      'InventoryID', 'HubID', 'AssetID', 'Manufacturer', 'Model', 'SerialNumber',
      'Processor', 'RAM', 'Storage', 'ScreenSize', 'OperatingSystem', 'Condition',
      'SellingPrice', 'DateAdded', 'Status', 'BuyerName', 'SaleDate', 'SalePrice',
      'Notes', 'OrderNumber', 'PurchaseOrderNumber', 'SalesOrderNumber',
      'DateCreated', 'DateModified'
    ],
    searchableColumns: ['AssetID', 'InventoryID', 'SerialNumber', 'Manufacturer', 'Model'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * Audit trail for the Inventory/Laptops modules (and anything else
   * that calls logAudit_() in AuditLog.gs going forward). One row per
   * change — who, what table/record/field, the before/after value,
   * and when. Never edited or deleted through the app; only ever
   * appended to.
   */
  AuditLog: {
    sheetName: 'AuditLog',
    primaryKey: 'AuditID',
    idPrefix: 'AUD',
    idPadding: 6,
    columns: [
      'AuditID', 'Timestamp', 'ActorEmail', 'ActorRole', 'Action',
      'TableName', 'RecordID', 'FieldName', 'OldValue', 'NewValue', 'HubID'
    ],
    searchableColumns: ['ActorEmail', 'RecordID', 'FieldName'],
    foreignKeys: {}
  },

  /**
   * ============================================================
   * PHASE 15 — Solar Community Hub Usage, Beneficiary & Computer
   * Tracking Module (see docs/SCH-Usage-Module-Spec.md)
   * ============================================================
   * Admin-editable classification lists, following the same
   * "small stable enum" pattern already used for Inventory's
   * Category/Condition/Status (fixed JS lists) where the set truly
   * never changes, but exposed as real tables here because these
   * ARE meant to be admin-editable without a code change (spec
   * Core Design Principle 7, "Config over code").
   */
  VisitorTypes: {
    sheetName: 'VisitorTypes',
    primaryKey: 'VisitorTypeID',
    idPrefix: 'VT',
    idPadding: 3,
    columns: ['VisitorTypeID', 'Name', 'Active', 'SortOrder', 'DateCreated', 'DateModified'],
    searchableColumns: ['Name'],
    foreignKeys: {}
  },

  AgeBands: {
    sheetName: 'AgeBands',
    primaryKey: 'AgeBandID',
    idPrefix: 'AB',
    idPadding: 3,
    columns: ['AgeBandID', 'Label', 'MinAge', 'MaxAge', 'IsYouth', 'Active', 'SortOrder', 'DateCreated', 'DateModified'],
    searchableColumns: ['Label'],
    foreignKeys: {}
  },

  Activities: {
    sheetName: 'Activities',
    primaryKey: 'ActivityID',
    idPrefix: 'ACT',
    idPadding: 3,
    columns: ['ActivityID', 'Name', 'Category', 'Active', 'SortOrder', 'DateCreated', 'DateModified'],
    searchableColumns: ['Name', 'Category'],
    foreignKeys: {}
  },

  /**
   * One row per Hub (not per weekday — see CONTINUATION.md/plan notes
   * for the MVP simplification rationale). Drives the Computer
   * Utilization Rate denominator (spec §25 KPI 17): OpenDays is a
   * comma-separated list of weekday numbers (0=Sun..6=Sat) the Hub is
   * open, paired with one OpenTime/CloseTime window.
   */
  HubSchedule: {
    sheetName: 'HubSchedule',
    primaryKey: 'ScheduleID',
    idPrefix: 'HSC',
    idPadding: 3,
    columns: ['ScheduleID', 'HubID', 'OpenDays', 'OpenTime', 'CloseTime', 'Effective', 'DateCreated', 'DateModified'],
    searchableColumns: [],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * HubID left blank on a row means the holiday applies to every Hub
   * (e.g. a global public holiday); set it to exclude only one Hub's
   * open-hours calculation on that date.
   */
  HubHolidays: {
    sheetName: 'HubHolidays',
    primaryKey: 'HolidayID',
    idPrefix: 'HOL',
    idPadding: 4,
    columns: ['HolidayID', 'HubID', 'Date', 'Reason', 'DateCreated'],
    searchableColumns: ['Reason'],
    foreignKeys: {}
  },

  /**
   * A person, org-wide. BeneficiaryID is location-independent and
   * sequential (Decision D-1 in the spec) — a person can visit many
   * Hubs over time, so the ID must never encode a single "home" hub.
   * HomeHubID is just a field, not baked into the ID. Data is
   * deliberately minimized (age GROUP not DOB, surname INITIAL not
   * full surname) per spec Core Design Principle 5.
   */
  Beneficiaries: {
    sheetName: 'Beneficiaries',
    primaryKey: 'BeneficiaryID',
    idPrefix: 'SCH-BEN-',
    idPadding: 6,
    columns: [
      'BeneficiaryID', 'FirstName', 'SurnameInitial', 'AgeGroup', 'Gender',
      'Country', 'Region', 'Community', 'EducationLevel', 'Occupation', 'UserCategory',
      'DisabilityInfo', 'Phone', 'Email', 'ConsentStatus', 'ConsentDate',
      'HomeHubID', 'RegistrationDate', 'QRToken', 'CreatedByEmail', 'CreatedByRole',
      'DateCreated', 'DateModified',
      'ClientUUID', 'DeviceID', 'SyncStatus',
      // Added later: exact Age + full LastName are now what registration
      // forms actually collect (see Beneficiaries.gs). AgeGroup/SurnameInitial
      // above are kept and auto-derived from these on every write — every
      // existing report/KPI/list that reads AgeGroup or SurnameInitial
      // keeps working unchanged, and doubles as the "anonymized" view
      // (band + initial) for Admin-level reporting, while Age/LastName hold
      // the full detail for operational use (confirming a returning visitor).
      'Age', 'LastName',
      // Drive file URL for a self-uploaded profile photo (PWA profile
      // screen) — never a raw image blob in the sheet itself, see
      // Sync.gs's syncProfileUpdate_.
      'PhotoUrl',
      // Added later: self-reported at registration, not derived from
      // visit history — see Beneficiaries.gs's validateBeneficiaryInput
      // and BENEFICIARY_DISTANCE_BANDS for the fixed option list.
      'DistanceFromHub', 'FirstTimeVisitor'
    ],
    searchableColumns: ['FirstName', 'SurnameInitial', 'LastName', 'Community', 'Phone', 'Email'],
    foreignKeys: {
      HomeHubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * Free-text feedback a beneficiary leaves before they go — captured
   * mainly from the PWA kiosk (per the welcome email's "share your
   * experience" prompt), but open to web capture too. Not tied to a
   * specific Visit/Session — just a person + a hub + what they said.
   */
  Feedback: {
    sheetName: 'Feedback',
    primaryKey: 'FeedbackID',
    idPrefix: 'FB-',
    idPadding: 6,
    columns: [
      'FeedbackID', 'BeneficiaryID', 'HubID', 'Message', 'Rating',
      'CreatedByEmail', 'CreatedByRole', 'DateCreated', 'DateModified',
      'ClientUUID', 'DeviceID', 'SyncStatus'
    ],
    searchableColumns: ['Message'],
    foreignKeys: {
      BeneficiaryID: { table: 'Beneficiaries', column: 'BeneficiaryID' },
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * One row per individual Hub Visit — the spec's primary measure of
   * reach/engagement. Never conflated with Computer Sessions: a
   * Visit can exist with zero, one, or many linked sessions
   * (ComputerUsed/NumComputersUsed are a summary here; the actual
   * ComputerSessions rows are the source of truth, added in
   * Milestone 4). This platform tracks individuals only — group
   * visit tracking was built in Phase 15 and later removed entirely
   * per product decision.
   */
  BeneficiaryVisits: {
    sheetName: 'BeneficiaryVisits',
    primaryKey: 'VisitID',
    idPrefix: 'VIS-',
    idPadding: 6,
    columns: [
      'VisitID', 'HubID', 'BeneficiaryID', 'Date', 'ArrivalTime', 'DepartureTime',
      'DurationMinutes', 'DepartureEstimated', 'VisitorType', 'Purpose', 'ProjectID',
      'ComputerUsed', 'NumComputersUsed', 'EntryMethod', 'Notes',
      'ClientUUID', 'DeviceID', 'SyncStatus', 'CreatedByEmail', 'CreatedByRole',
      'DateCreated', 'DateModified',
      // Set when this visit was created by joining an open ActivitySessions
      // row (ActivitySessions.gs) rather than the individual visit form —
      // blank for every ordinary visit.
      'SessionID'
    ],
    searchableColumns: ['Purpose', 'Notes'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' },
      BeneficiaryID: { table: 'Beneficiaries', column: 'BeneficiaryID' },
      ProjectID: { table: 'Projects', column: 'ProjectID' },
      SessionID: { table: 'ActivitySessions', column: 'SessionID' }
    }
  },

  /**
   * Many-to-many activity tagging for individual Visits. VisitType is
   * 'Individual' for an ordinary visit, 'Session' for one created by
   * joining an open ActivitySessions row — the column was kept (rather
   * than dropped as unused) specifically so a second VisitType could be
   * added later without a schema change; see also the note below on why
   * this isn't the same thing as the removed CommunityGroups/GroupVisits
   * concept. (Individual beneficiaries are still what's tracked — a
   * Session is a scheduled Activity instance people join one at a time,
   * each still their own Visit row.)
   */
  VisitActivities: {
    sheetName: 'VisitActivities',
    primaryKey: 'VisitActivityID',
    idPrefix: 'VA',
    idPadding: 6,
    columns: ['VisitActivityID', 'VisitType', 'VisitID', 'ActivityID'],
    searchableColumns: [],
    foreignKeys: {
      ActivityID: { table: 'Activities', column: 'ActivityID' }
    }
  },

  /**
   * A Hub Manager opens one of these against an existing Activity so
   * beneficiaries can one-tap "join" it from the PWA instead of each
   * picking it individually — see ActivitySessions.gs. Closing it
   * bulk-sets DepartureTime on every still-open linked BeneficiaryVisits
   * row (DepartureEstimated: true, since a bulk close is an
   * approximation of each person's actual departure, not a reported one).
   */
  ActivitySessions: {
    sheetName: 'ActivitySessions',
    primaryKey: 'SessionID',
    idPrefix: 'GSN',
    idPadding: 4,
    columns: ['SessionID', 'HubID', 'ActivityID', 'Status', 'OpenedAt', 'ClosedAt', 'OpenedByEmail', 'ClosedByEmail'],
    searchableColumns: [],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' },
      ActivityID: { table: 'Activities', column: 'ActivityID' }
    }
  },

  /**
   * A thin registry row over an existing Inventory item (Category
   * Desktop Computers/Laptops — same COMPUTER_CATEGORIES already
   * used by HubHealth.gs) — NOT a duplicate status source. Session
   * eligibility always reads the live Inventory.Status; this table
   * only exists to give a stable ComputerID for usage tracking.
   * Lazily created the first time a hub's computer Inventory item is
   * seen (see Computers.gs) — natural-key ID, hub-scoped format
   * (e.g. H001-PC001), not the generic auto-increment.
   */
  Computers: {
    sheetName: 'Computers',
    primaryKey: 'ComputerID',
    autoId: false,
    columns: [
      'ComputerID', 'InventoryID', 'HubID', 'DeviceType', 'LastActiveDate', 'DateCreated', 'DateModified',
      // Added later: ad hoc computers (typed in by a beneficiary on the
      // PWA, not pre-registered in Inventory) have InventoryID blank and
      // carry their display name here instead — see
      // findOrCreateComputerByName_ in Computers.gs. Inventory-backed
      // computers leave this blank and keep using the joined ItemName.
      'Name'
    ],
    searchableColumns: [],
    foreignKeys: {
      InventoryID: { table: 'Inventory', column: 'InventoryID' },
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * One row per computer login/logout — the spec's primary measure
   * of computer utilization. Always identifies Hub + Computer; links
   * to a Visit when one is open for that Beneficiary/Hub/day (§14).
   */
  ComputerSessions: {
    sheetName: 'ComputerSessions',
    primaryKey: 'SessionID',
    idPrefix: 'SES-',
    idPadding: 6,
    columns: [
      'SessionID', 'VisitID', 'BeneficiaryID', 'HubID', 'ComputerID',
      'LoginTime', 'LogoutTime', 'DurationMinutes', 'DurationEstimated',
      'ActivityID', 'ProjectID', 'Status', 'IdleMinutes', 'EntryMethod',
      'ClientUUID', 'DeviceID', 'ClientCapturedAt', 'ServerReceivedAt', 'NormalizedTime', 'SyncStatus',
      'CreatedByEmail', 'CreatedByRole', 'DateCreated', 'DateModified'
    ],
    searchableColumns: [],
    foreignKeys: {
      VisitID: { table: 'BeneficiaryVisits', column: 'VisitID' },
      BeneficiaryID: { table: 'Beneficiaries', column: 'BeneficiaryID' },
      HubID: { table: 'Hubs', column: 'HubID' },
      ComputerID: { table: 'Computers', column: 'ComputerID' },
      ActivityID: { table: 'Activities', column: 'ActivityID' }
    }
  },

  /**
   * Pre-aggregated KPI cache — dashboards read from here, not from
   * scanning raw Visits/ComputerSessions rows (spec §33
   * performance requirement). Rows are recomputed (deleted +
   * reinserted) each time getHubUsageDashboard/getGlobalUsageDashboard
   * runs — see UsageKPIs.gs for why "recompute on read" was chosen
   * over write-triggered incremental updates for this MVP.
   */
  KPIResults: {
    sheetName: 'KPIResults',
    primaryKey: 'KPIResultID',
    idPrefix: 'KPI',
    idPadding: 6,
    columns: ['KPIResultID', 'KPICode', 'Level', 'ScopeID', 'PeriodType', 'PeriodStart', 'PeriodEnd', 'Value', 'Numerator', 'Denominator', 'ComputedAt'],
    searchableColumns: [],
    foreignKeys: {}
  },

  /** Data-quality findings queue (spec §22) — Status Open/Resolved/Ignored, never deleted, only resolved. */
  DataQualityIssues: {
    sheetName: 'DataQualityIssues',
    primaryKey: 'IssueID',
    idPrefix: 'DQI',
    idPadding: 5,
    columns: ['IssueID', 'EntityType', 'EntityID', 'HubID', 'IssueType', 'Severity', 'Detail', 'Status', 'DetectedAt', 'ResolvedByEmail', 'ResolvedAt'],
    searchableColumns: ['EntityID', 'IssueType', 'Detail'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * ============================================================
   * PHASE 16 — Training/Program Attendance, AI Analytics
   * ============================================================
   * A reusable curriculum entry (e.g. "AI Literacy 101") — small
   * admin-editable config list, same shape as Activities. No
   * ProgramID FK: this platform has no separate "Programs" concept
   * above Projects, and a reusable course doesn't map cleanly to one
   * dated Projects report anyway (see Phase 16 plan notes).
   */
  TrainingCourses: {
    sheetName: 'TrainingCourses',
    primaryKey: 'CourseID',
    idPrefix: 'CRS',
    idPadding: 3,
    columns: ['CourseID', 'Name', 'Category', 'Active', 'SortOrder', 'DateCreated', 'DateModified'],
    searchableColumns: ['Name', 'Category'],
    foreignKeys: {}
  },

  /**
   * One dated delivery of a TrainingCourse at a Hub. TrainerName is
   * free text, not an FK — this platform has no generic Users table
   * spanning Admins/HubManagers to reference (see Phase 16 plan notes).
   */
  TrainingSessions: {
    sheetName: 'TrainingSessions',
    primaryKey: 'TrainingSessionID',
    idPrefix: 'TRS',
    idPadding: 5,
    columns: [
      'TrainingSessionID', 'CourseID', 'HubID', 'Date', 'StartTime', 'EndTime',
      'TrainerName', 'PlannedParticipants', 'Notes', 'CreatedByEmail', 'CreatedByRole',
      'DateCreated', 'DateModified'
    ],
    searchableColumns: ['TrainerName', 'Notes'],
    foreignKeys: {
      CourseID: { table: 'TrainingCourses', column: 'CourseID' },
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /** One row per beneficiary marked against a TrainingSession. */
  Attendance: {
    sheetName: 'Attendance',
    primaryKey: 'AttendanceID',
    idPrefix: 'ATT',
    idPadding: 6,
    columns: ['AttendanceID', 'TrainingSessionID', 'BeneficiaryID', 'VisitID', 'Present', 'Completed', 'DateCreated'],
    searchableColumns: [],
    foreignKeys: {
      TrainingSessionID: { table: 'TrainingSessions', column: 'TrainingSessionID' },
      BeneficiaryID: { table: 'Beneficiaries', column: 'BeneficiaryID' },
      VisitID: { table: 'BeneficiaryVisits', column: 'VisitID' }
    }
  },

  /**
   * AI-generated narrative summaries (spec §27) — aggregate KPI
   * inputs only, never row-level PII. Reviewed defaults false; an
   * Admin must mark it reviewed before treating it as usable
   * externally. Named AIInsights, not the spec's generic "Reports"
   * (see Phase 16 plan notes — exports are already solved separately).
   */
  AIInsights: {
    sheetName: 'AIInsights',
    primaryKey: 'InsightID',
    idPrefix: 'AII',
    idPadding: 5,
    columns: [
      'InsightID', 'Level', 'ScopeID', 'PeriodType', 'PeriodStart', 'PeriodEnd',
      'NarrativeText', 'InputDataJSON', 'AnomalyFlags', 'GeneratedAt',
      'Reviewed', 'ReviewedByEmail', 'ReviewedAt'
    ],
    searchableColumns: [],
    foreignKeys: {}
  },

  /**
   * ============================================================
   * PHASE 16 MILESTONE C — Offline sync (see Sync.gs)
   * ============================================================
   * One row per provisioned offline-capture device (a PWA install or
   * a future desktop agent). Keyed by a caller-supplied DeviceID
   * (natural key, same pattern as HubManagers/Admins) — the API key
   * is salted+hashed with the exact same hashPassword()/
   * verifyPassword() helpers used for human logins, never stored
   * plain.
   */
  SyncDevices: {
    sheetName: 'SyncDevices',
    primaryKey: 'DeviceID',
    autoId: false,
    columns: ['DeviceID', 'HubID', 'DeviceLabel', 'APIKeyHash', 'APIKeySalt', 'Active', 'LastSyncAt', 'DateCreated'],
    searchableColumns: ['DeviceID', 'DeviceLabel'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /** One row per sync batch received — audit trail for troubleshooting offline sync issues. */
  SynchronizationLogs: {
    sheetName: 'SynchronizationLogs',
    primaryKey: 'SyncLogID',
    idPrefix: 'SYL',
    idPadding: 6,
    columns: ['SyncLogID', 'DeviceID', 'BatchID', 'ReceivedAt', 'RecordsTotal', 'RecordsWritten', 'Duplicates', 'Conflicts', 'Errors', 'Detail'],
    searchableColumns: ['DeviceID', 'BatchID'],
    foreignKeys: {
      DeviceID: { table: 'SyncDevices', column: 'DeviceID' }
    }
  },

  /**
   * Self-service device provisioning (DeviceRequests.gs): a kiosk that
   * doesn't have credentials yet submits a request naming its Hub; the
   * Hub's Manager(s) approve/reject from a bell notification. Status
   * moves Pending -> Approved|Rejected|Expired, then Approved -> Claimed
   * the instant the kiosk successfully reads the one-time plaintext key
   * back (IssuedApiKeyPlaintext is cleared in that same call) — this is
   * the only place a plaintext API key is ever stored, and only briefly.
   */
  DeviceRequests: {
    sheetName: 'DeviceRequests',
    primaryKey: 'RequestID',
    idPrefix: 'DRQ',
    idPadding: 6,
    columns: [
      'RequestID', 'HubID', 'DeviceLabel', 'ComposedDeviceID', 'ConfirmationCode', 'Status',
      'ExpiresAt', 'ApprovedByEmail', 'ApprovedAt', 'IssuedApiKeyPlaintext', 'DateCreated', 'DateModified'
    ],
    searchableColumns: ['DeviceLabel', 'ComposedDeviceID'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * ============================================================
   * PHASE 17 — Financial Management & Project Funds Module
   * ============================================================
   * A project financial MONITORING layer, not an accounting system.
   * See FINANCE_MODULE_INSTRUCTIONS.md for the full design. Money
   * always exists in exactly one of four states — Pending Approval /
   * Committed / Paid / Void — computed on read from these source
   * tables by FinanceBalance.gs (no separate stored ledger to drift
   * out of sync; see that file's header comment). No finance row is
   * ever hard-deleted — a "Cancelled" Status is the only way to
   * retire a record, same principle as DataQualityIssues' Ignored.
   *
   * ExpenseCategory fields below store the category NAME (a plain
   * string), the same convention BeneficiaryVisits.VisitorType
   * already uses for VisitorTypes — not a CategoryID FK — so no
   * join is needed to display or filter by category.
   */

  /** Admin-editable expense/income category list — same shape as Activities/VisitorTypes. */
  FinanceCategories: {
    sheetName: 'FinanceCategories',
    primaryKey: 'CategoryID',
    idPrefix: 'FC',
    idPadding: 3,
    columns: ['CategoryID', 'Name', 'Type', 'Active', 'SortOrder', 'DateCreated', 'DateModified'],
    searchableColumns: ['Name'],
    foreignKeys: {}
  },

  /**
   * A lightweight project-staff master (NOT a login account) that
   * Salaries/Reimbursements link to by StaffID. Deliberately separate
   * from Admins/HubManagers — most paid project staff are not system
   * users. Email is optional (for notifications only, never a login).
   */
  FinanceStaff: {
    sheetName: 'FinanceStaff',
    primaryKey: 'StaffID',
    idPrefix: 'STF',
    idPadding: 4,
    columns: ['StaffID', 'FullName', 'StaffNumber', 'RoleTitle', 'HubID', 'Email', 'Status', 'DateCreated', 'DateModified'],
    searchableColumns: ['FullName', 'StaffNumber', 'RoleTitle'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * A bank/mobile-money account holding project funds. AccountNumber
   * is stored in full but MUST NEVER be returned to the client raw —
   * every read path returns AccountNumberMasked instead (see
   * maskAccountNumber_ in FinanceAccounts.gs). Currency defaults to
   * the system currency (Settings.gs) but is stored per-account since
   * a Hub could eventually hold a foreign-currency account.
   */
  FinancialAccounts: {
    sheetName: 'FinancialAccounts',
    primaryKey: 'AccountID',
    idPrefix: 'FA',
    idPadding: 3,
    columns: [
      'AccountID', 'AccountName', 'BankName', 'AccountNumber', 'Currency', 'AccountType',
      'HubID', 'ProjectID', 'OpeningBalance', 'OpeningBalanceDate', 'Status',
      'CreatedByEmail', 'DateCreated', 'DateModified'
    ],
    searchableColumns: ['AccountName', 'BankName'],
    foreignKeys: {
      HubID: { table: 'Hubs', column: 'HubID' },
      ProjectID: { table: 'Projects', column: 'ProjectID' }
    }
  },

  /**
   * Funding transferred INTO a FinancialAccount (a grant instalment,
   * project advance, ...). Only Status='Confirmed' rows count toward
   * the balance engine — 'Recorded' exists so a funding entry can be
   * logged the moment it's known about without yet asserting the
   * transfer has cleared.
   */
  FundingTransactions: {
    sheetName: 'FundingTransactions',
    primaryKey: 'FundingID',
    idPrefix: 'FND',
    idPadding: 4,
    columns: [
      'FundingID', 'DateReceived', 'Amount', 'Currency', 'FundingSource', 'Donor',
      'ProjectID', 'HubID', 'AccountID', 'ReferenceNumber', 'Description', 'DocumentID',
      'Status', 'EnteredByEmail', 'DateEntered', 'DateCreated', 'DateModified'
    ],
    searchableColumns: ['FundingSource', 'Donor', 'ReferenceNumber', 'Description'],
    foreignKeys: {
      ProjectID: { table: 'Projects', column: 'ProjectID' },
      HubID: { table: 'Hubs', column: 'HubID' },
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' },
      DocumentID: { table: 'FinancialDocuments', column: 'DocumentID' }
    }
  },

  /**
   * Raising an invoice deducts NOTHING from any balance (see §3 of
   * FINANCE_MODULE_INSTRUCTIONS.md). Approval moves its amount into
   * "Committed"; PaymentStatus='Paid' moves it into actual
   * expenditure. Status and PaymentStatus are deliberately two
   * separate fields — an invoice can be Approved and still Unpaid.
   */
  Invoices: {
    sheetName: 'Invoices',
    primaryKey: 'InvoiceID',
    idPrefix: 'INV',
    idPadding: 4,
    columns: [
      'InvoiceID', 'InvoiceNumber', 'InvoiceDate', 'DateSubmitted', 'SupplierName', 'SupplierContact',
      'SupplierInvoiceRef', 'ProjectID', 'HubID', 'ExpenseCategory', 'BudgetLineID', 'Description',
      'Amount', 'TaxAmount', 'TotalAmount', 'Currency', 'PaymentMethod', 'AccountID', 'InvoiceDocumentID',
      'Status', 'SubmittedByEmail', 'SubmittedByRole', 'ReviewedByEmail', 'ApprovedByEmail', 'ApprovalDate',
      'RejectionReason', 'PaymentStatus', 'PaymentDate', 'PaymentReference', 'Notes',
      'DateCreated', 'DateModified',
      // Appended for the branded, generated line-item invoice (Module:
      // invoice generation). LineItemsJSON holds the printed rows
      // [{description, unitCost, qtyRate, amount}]; Discount/TaxRate feed
      // the totals panel. Amount stays the subtotal, TotalAmount the
      // computed grand total — both still drive the finance/approval flow.
      'LineItemsJSON', 'Discount', 'TaxRate',
      // InvoiceTag: an optional free-choice tag (e.g. "Monthly Stipends")
      // a Hub Manager picks at submission — see isStipendInvoice_ in
      // Invoices.gs. Together with ExpenseCategory === 'Stipend/Salaries'
      // it decides whether an invoice is filed under the Admin's Salaries
      // tab instead of the plain Invoices tab.
      'InvoiceTag'
    ],
    searchableColumns: ['InvoiceNumber', 'SupplierName', 'Description'],
    foreignKeys: {
      ProjectID: { table: 'Projects', column: 'ProjectID' },
      HubID: { table: 'Hubs', column: 'HubID' },
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' },
      BudgetLineID: { table: 'BudgetLines', column: 'BudgetLineID' },
      InvoiceDocumentID: { table: 'FinancialDocuments', column: 'DocumentID' }
    }
  },

  /** Same Status/PaymentStatus split as Invoices. StaffID is optional (a vendor expense has no staff payee). */
  Expenses: {
    sheetName: 'Expenses',
    primaryKey: 'ExpenseID',
    idPrefix: 'EXP',
    idPadding: 4,
    columns: [
      'ExpenseID', 'Date', 'PayeeName', 'StaffID', 'Description', 'Amount', 'TaxAmount', 'TotalAmount',
      'Currency', 'ProjectID', 'HubID', 'ExpenseCategory', 'BudgetLineID', 'PaymentMethod', 'AccountID',
      'ReceiptDocumentID', 'Status', 'SubmittedByEmail', 'SubmittedByRole', 'ApprovedByEmail', 'ApprovalDate',
      'RejectionReason', 'PaymentStatus', 'PaymentDate', 'PaymentReference', 'Notes',
      'DateCreated', 'DateModified'
    ],
    searchableColumns: ['PayeeName', 'Description'],
    foreignKeys: {
      StaffID: { table: 'FinanceStaff', column: 'StaffID' },
      ProjectID: { table: 'Projects', column: 'ProjectID' },
      HubID: { table: 'Hubs', column: 'HubID' },
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' },
      BudgetLineID: { table: 'BudgetLines', column: 'BudgetLineID' },
      ReceiptDocumentID: { table: 'FinancialDocuments', column: 'DocumentID' }
    }
  },

  /**
   * Individual salary rows are Admin-only to READ (never sent to a
   * Hub Manager client) — see getMyHubStaffCostSummary in
   * Salaries.gs for the aggregate a manager sees instead.
   */
  Salaries: {
    sheetName: 'Salaries',
    primaryKey: 'SalaryID',
    idPrefix: 'SAL',
    idPadding: 4,
    columns: [
      'SalaryID', 'StaffID', 'Month', 'ProjectID', 'HubID', 'GrossAmount', 'Allowances', 'Deductions',
      'NetProjectCost', 'Currency', 'AccountID', 'PayrollDocumentID', 'Status', 'ApprovedByEmail', 'ApprovalDate',
      'PaymentStatus', 'PaymentDate', 'PaymentReference', 'DateCreated', 'DateModified',
      // Added before first use (Salaries.gs, Phase 17 Step 6): who
      // created the Draft, so approveSalary can enforce the same
      // separation-of-duties rule as every other finance approval
      // (assertNotSelfApproval_ in FinanceCommon.gs) even though
      // Salaries has no multi-role submit/approve split otherwise.
      'CreatedByEmail'
    ],
    searchableColumns: [],
    foreignKeys: {
      StaffID: { table: 'FinanceStaff', column: 'StaffID' },
      ProjectID: { table: 'Projects', column: 'ProjectID' },
      HubID: { table: 'Hubs', column: 'HubID' },
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' },
      PayrollDocumentID: { table: 'FinancialDocuments', column: 'DocumentID' }
    }
  },

  /** A staff member reimbursed for a personal spend on an approved project expense. ApprovedAmount may differ from Amount requested. */
  Reimbursements: {
    sheetName: 'Reimbursements',
    primaryKey: 'ReimbursementID',
    idPrefix: 'RMB',
    idPadding: 4,
    columns: [
      'ReimbursementID', 'StaffID', 'Date', 'ProjectID', 'HubID', 'ActivityRef', 'ExpenseCategory',
      'BudgetLineID', 'Description', 'Amount', 'Currency', 'Reason', 'ReceiptDocumentID', 'Status',
      'ApprovedAmount', 'ApprovedByEmail', 'ApprovalDate', 'RejectionReason',
      'PaymentStatus', 'PaymentDate', 'PaymentReference', 'DateCreated', 'DateModified',
      // Added before first use (Reimbursements.gs, Phase 17 Step 5):
      // AccountID/PaymentMethod match Invoices/Expenses so the balance
      // engine (FinanceBalance.gs) can attribute a paid/committed
      // reimbursement to the right account — without AccountID here a
      // reimbursement would silently never count toward any account's
      // balance. SubmittedByEmail/SubmittedByRole match Invoices/
      // Expenses too, needed for the self-approval guard.
      'AccountID', 'PaymentMethod', 'SubmittedByEmail', 'SubmittedByRole'
    ],
    searchableColumns: ['Description', 'Reason'],
    foreignKeys: {
      StaffID: { table: 'FinanceStaff', column: 'StaffID' },
      ProjectID: { table: 'Projects', column: 'ProjectID' },
      HubID: { table: 'Hubs', column: 'HubID' },
      ReceiptDocumentID: { table: 'FinancialDocuments', column: 'DocumentID' },
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' }
    }
  },

  /** A named budget for one Project (and optionally scoped to one Hub) for one financial year. Category totals live in BudgetLines. */
  Budgets: {
    sheetName: 'Budgets',
    primaryKey: 'BudgetID',
    idPrefix: 'BGT',
    idPadding: 3,
    columns: ['BudgetID', 'ProjectID', 'HubID', 'Name', 'FinancialYear', 'TotalBudget', 'Currency', 'Status', 'DateCreated', 'DateModified'],
    searchableColumns: ['Name'],
    foreignKeys: {
      ProjectID: { table: 'Projects', column: 'ProjectID' },
      HubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /** One row per expense-category allocation within a Budget — the Budget-vs-Actual dashboard's unit of comparison. */
  BudgetLines: {
    sheetName: 'BudgetLines',
    primaryKey: 'BudgetLineID',
    idPrefix: 'BGL',
    idPadding: 4,
    columns: ['BudgetLineID', 'BudgetID', 'ExpenseCategory', 'BudgetedAmount', 'Currency', 'DateCreated', 'DateModified'],
    searchableColumns: ['ExpenseCategory'],
    foreignKeys: {
      BudgetID: { table: 'Budgets', column: 'BudgetID' }
    }
  },

  /**
   * Metadata for a financial supporting document. The Drive file
   * itself is stored PRIVATE (no ANYONE_WITH_LINK) in a single
   * folder set once via Script Properties (FINANCE_DRIVE_FOLDER_ID)
   * — see FinanceDocuments.gs. DriveFileID never leaves the server;
   * only this row's DocumentID is ever sent to the client, and the
   * file bytes are served through the access-checked
   * getFinancialDocument() endpoint. LinkedTable/LinkedRecordID
   * point at whichever finance row this document backs (an Invoice,
   * Expense, Reimbursement, FundingTransaction, Salary payroll
   * record, or BalanceAdjustment).
   */
  FinancialDocuments: {
    sheetName: 'FinancialDocuments',
    primaryKey: 'DocumentID',
    idPrefix: 'DOC',
    idPadding: 4,
    columns: [
      'DocumentID', 'DriveFileID', 'FileName', 'MimeType', 'LinkedTable', 'LinkedRecordID',
      'DocumentType', 'UploadedByEmail', 'DateUploaded', 'DateCreated', 'DateModified'
    ],
    searchableColumns: ['FileName', 'LinkedRecordID'],
    foreignKeys: {}
  },

  /**
   * A controlled, audited correction to an account's calculated
   * balance (e.g. a bank charge the source tables don't otherwise
   * capture). Amount is signed (+/-). Requires a Reason and an
   * approver different from the person who raised it, same
   * self-approval rule as every other finance approval.
   */
  BalanceAdjustments: {
    sheetName: 'BalanceAdjustments',
    primaryKey: 'AdjustmentID',
    idPrefix: 'ADJ',
    idPadding: 4,
    columns: [
      'AdjustmentID', 'Date', 'AccountID', 'Amount', 'Reason', 'DocumentID', 'MadeByEmail',
      'ApprovedByEmail', 'ApprovalDate', 'Status', 'DateCreated', 'DateModified'
    ],
    searchableColumns: ['Reason'],
    foreignKeys: {
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' },
      DocumentID: { table: 'FinancialDocuments', column: 'DocumentID' }
    }
  },

  /**
   * ============================================================
   * PHASE 17 STEP — Bank Reconciliation (Finance Phase 2)
   * ============================================================
   * A BankStatements row is one uploaded statement period for one
   * account (Admin types the OpeningBalance/ClosingBalance straight
   * off the physical/PDF statement — this table doesn't try to parse
   * those from the file). FileDocumentID links to the private,
   * server-gated FinancialDocuments upload of the raw statement file
   * for evidence, kept separate from the parsed BankTransactions rows.
   */
  BankStatements: {
    sheetName: 'BankStatements',
    primaryKey: 'StatementID',
    idPrefix: 'BST',
    idPadding: 4,
    columns: [
      'StatementID', 'AccountID', 'StatementDate', 'OpeningBalance', 'ClosingBalance', 'Currency',
      'FileDocumentID', 'UploadedByEmail', 'DateUploaded', 'Status', 'DateCreated', 'DateModified'
    ],
    searchableColumns: [],
    foreignKeys: {
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' },
      FileDocumentID: { table: 'FinancialDocuments', column: 'DocumentID' }
    }
  },

  /**
   * One parsed row per line of an imported bank statement CSV.
   * MatchStatus starts 'Unmatched'; autoMatchBankTransactions_ (see
   * BankReconciliation.gs) and manual matching move it to 'Matched'
   * (with MatchedTable/MatchedRecordID pointing at the Paid
   * Invoice/Expense/Reimbursement/Salary/FundingTransaction it
   * corresponds to) or 'Ignored' (reviewed, deliberately has no
   * matching system record — e.g. a bank fee).
   */
  BankTransactions: {
    sheetName: 'BankTransactions',
    primaryKey: 'BankTransactionID',
    idPrefix: 'BTX',
    idPadding: 6,
    columns: [
      'BankTransactionID', 'StatementID', 'AccountID', 'Date', 'Description', 'Amount',
      'MatchedTable', 'MatchedRecordID', 'MatchStatus', 'DateCreated'
    ],
    searchableColumns: ['Description'],
    foreignKeys: {
      StatementID: { table: 'BankStatements', column: 'StatementID' },
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' }
    }
  },

  /**
   * One row per reconciliation attempt for a statement. SystemBalance
   * is the CURRENT computed balance at the moment the reconciliation
   * is run (see FinanceBalance.gs) compared against the statement's
   * own ClosingBalance — an intentional MVP simplification, not a
   * historical point-in-time ledger walk (see BankReconciliation.gs
   * header comment). A mismatch is flagged for a human to investigate
   * and resolve; it is NEVER used to silently overwrite any balance.
   */
  Reconciliations: {
    sheetName: 'Reconciliations',
    primaryKey: 'ReconciliationID',
    idPrefix: 'REC',
    idPadding: 4,
    columns: [
      'ReconciliationID', 'AccountID', 'StatementID', 'StatementDate', 'SystemBalance', 'StatementBalance',
      'Difference', 'Status', 'Notes', 'ReconciledByEmail', 'ReconciledAt', 'DateCreated', 'DateModified'
    ],
    searchableColumns: ['Notes'],
    foreignKeys: {
      AccountID: { table: 'FinancialAccounts', column: 'AccountID' },
      StatementID: { table: 'BankStatements', column: 'StatementID' }
    }
  },

  /**
   * A logged exchange rate: "1 CurrencyCode = Rate [system currency]"
   * (the system currency itself — Settings.gs — never needs a row; its
   * implicit rate is always 1). APPEND-ONLY HISTORY, never edited or
   * deleted: setExchangeRate() always inserts a new row rather than
   * overwriting an old one, so a rate correction is itself an audited
   * event, not a silent edit. getEffectiveExchangeRate_() (see
   * ExchangeRates.gs) always uses the most-recently-dated row for a
   * currency, so "updating" a rate is just logging a newer one.
   */
  ExchangeRates: {
    sheetName: 'ExchangeRates',
    primaryKey: 'ExchangeRateID',
    idPrefix: 'FX',
    idPadding: 4,
    columns: ['ExchangeRateID', 'CurrencyCode', 'Rate', 'RateDate', 'Source', 'EnteredByEmail', 'DateCreated', 'DateModified'],
    searchableColumns: ['CurrencyCode', 'Source'],
    foreignKeys: {}
  },

  /**
   * A notification is addressed EITHER to one specific person
   * (TargetEmail set — "your invoice was approved") OR broadcast to a
   * role, optionally scoped to one hub (TargetEmail blank,
   * TargetRole='Admin'/'HubManager' [+ TargetHubID] — "an invoice
   * needs your approval", seen by every Admin). getMyNotifications()
   * in Notifications.gs matches a caller against whichever applies.
   *
   * ReadByEmails is a comma-separated list of who has read/dismissed
   * THIS row — necessary because a broadcast notification has more
   * than one possible reader, each of whom can read it independently,
   * without needing a separate join table for one boolean per reader.
   */
  Notifications: {
    sheetName: 'Notifications',
    primaryKey: 'NotificationID',
    idPrefix: 'NTF',
    idPadding: 6,
    columns: [
      'NotificationID', 'Type', 'Severity', 'Message', 'TargetEmail', 'TargetRole', 'TargetHubID',
      'RelatedTable', 'RelatedRecordID', 'ReadByEmails', 'CreatedAt',
      // Appended for Module 3 (roles): further narrows a TargetRole:'Admin'
      // broadcast by AccessLevel — comma-separated (e.g.
      // 'SuperAdmin,CountryDirector,Accountant'). Blank means every Admin
      // AccessLevel sees it (the pre-Module-3 behavior, still correct for
      // anything not Finance/M&E-specific). See notificationVisibleTo_ in
      // Notifications.gs and FINANCE_ACCESS_LEVELS/ME_ACCESS_LEVELS there.
      'TargetAccessLevels'
    ],
    searchableColumns: ['Message'],
    foreignKeys: {
      TargetHubID: { table: 'Hubs', column: 'HubID' }
    }
  },

  /**
   * One row per conversation between exactly two people (any Admin
   * AccessLevel <-> any Hub Manager, or Admin <-> Admin) — see Chat.gs.
   * ParticipantA/BEmail are canonically ordered (alphabetical) so the
   * same pair always resolves to the same thread; ParticipantA/
   * BLastReadAt track each side's own read position, so "unread count"
   * never needs a per-message read flag.
   */
  ChatThreads: {
    sheetName: 'ChatThreads',
    primaryKey: 'ThreadID',
    idPrefix: 'THR',
    idPadding: 5,
    columns: [
      'ThreadID', 'ParticipantAEmail', 'ParticipantBEmail',
      'LastMessageAt', 'LastMessagePreview',
      'ParticipantALastReadAt', 'ParticipantBLastReadAt', 'DateCreated'
    ],
    searchableColumns: [],
    foreignKeys: {}
  },

  /**
   * Individual messages within a ChatThread — see Chat.gs's
   * sendChatMessage/getThreadMessages. Deliberately named SentAt, not
   * DateCreated: DB.insert() force-overwrites any column literally named
   * DateCreated/DateModified with a raw Date object regardless of what's
   * passed in, and _rowToObject() then truncates a Date-typed cell to a
   * bare 'yyyy-MM-dd' on read (see Database.gs's own header comment on
   * this) — fine for ordinary record-creation bookkeeping, but it would
   * silently drop every message's time-of-day, breaking same-day
   * ordering and display for what's supposed to be a chat. Stored as an
   * ISO string instead, same convention as Sessions.ExpiresAt.
   */
  ChatMessages: {
    sheetName: 'ChatMessages',
    primaryKey: 'MessageID',
    idPrefix: 'MSG',
    idPadding: 6,
    columns: ['MessageID', 'ThreadID', 'SenderEmail', 'Body', 'SentAt'],
    searchableColumns: ['Body'],
    foreignKeys: {
      ThreadID: { table: 'ChatThreads', column: 'ThreadID' }
    }
  }

  // Future modules plug in here following the same shape:
  // Indicators, Donors, Trainings, MonitoringVisits, Reports,
  // Evidence, Roles, Permissions ...
};
